name: Run tests

on: [push]

jobs:  

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node-version: [8.x, 10.x, 12.x, 13.x]

        mongodb-version: [3.6, 4.0, 4.2]

    steps:

     - name: start MongoDB v${{ matrix.mongodb-version }}
     uses: supercharge/mongodb-github-action@1.2.0
    with:
      mongodb-version: ${{ matrix.mongodb-version }}

     - run: echo "done"