name: Memehub Apk Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Build the app
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
       #run:|cd app run: bash ./gradlew assembleDebug --stacktrace

      - name: Create APK release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            This is the release of the Android app.
          draft: false
          prerelease: false

      - name: Upload APK file
        uses: actions/upload-release-asset@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/debug/memehub-debug.apk
          asset_name: memehub-debug.apk
          asset_content_type: application/vnd.android.package-archive
