name: Clear and Regenerate

on:
  push:
    branches:
      - main

jobs:
  clear_and_regenerate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clear existing files
      run: |
        # Remove any existing files you want to clear
        rm -rf app/src
      # Continue with other cleanup steps if needed

    #- name: Set up JDK 11
      #uses: actions/setup-java@v2
     # with:
       # java-version: 11

   # - name: Build with Gradle
    #  run: |
        # Navigate to your project directory
     #   cd <your_project_directory>
        # Build your project
        ./gradlew build

    # Add more steps if necessary, such as deploying your project