name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set execute permission for Gradle wrapper script
    - name: Set execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        architecture: 'x64'
        check-latest: false
        overwrite: true
        job-status: success

    - name: Build with Gradle
      run: ./gradlew assembleDebug --warning-mode all

    - name: Create directory for artifacts
      run: mkdir -p artifacts

    - name: Copy APK to artifacts directory
      run: cp app/build/outputs/apk/debug/app-debug.apk artifacts/

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: artifacts/