name: Android CI

on:
  push:
    branches:
      - main

jobs:
  buildMinApi26:
  name: Build minApi26 debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
    
         - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-minApi26-debug
          path: app/build/minApi26/debug
  